lib: [
  "_build/install/default/lib/pacml/Command.ml"
  "_build/install/default/lib/pacml/Logic.ml"
  "_build/install/default/lib/pacml/META"
  "_build/install/default/lib/pacml/State.ml"
  "_build/install/default/lib/pacml/dune-package"
  "_build/install/default/lib/pacml/game.a"
  "_build/install/default/lib/pacml/game.cma"
  "_build/install/default/lib/pacml/game.cmi"
  "_build/install/default/lib/pacml/game.cmt"
  "_build/install/default/lib/pacml/game.cmx"
  "_build/install/default/lib/pacml/game.cmxa"
  "_build/install/default/lib/pacml/game.ml"
  "_build/install/default/lib/pacml/game__Command.cmi"
  "_build/install/default/lib/pacml/game__Command.cmt"
  "_build/install/default/lib/pacml/game__Command.cmx"
  "_build/install/default/lib/pacml/game__Logic.cmi"
  "_build/install/default/lib/pacml/game__Logic.cmt"
  "_build/install/default/lib/pacml/game__Logic.cmx"
  "_build/install/default/lib/pacml/game__State.cmi"
  "_build/install/default/lib/pacml/game__State.cmt"
  "_build/install/default/lib/pacml/game__State.cmx"
  "_build/install/default/lib/pacml/opam"
]
libexec: [
  "_build/install/default/lib/pacml/game.cmxs"
]
bin: [
  "_build/install/default/bin/pacml"
]
